version: '3.7'

services:

  philoart:
    # image: nodejs:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: philoart
    volumes:
      - '.:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true